name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: secrets
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
        ZENBOT_DB_FILE: ${{ secrets.ZENBOT_DB_FILE }}
      run: |
        pwd
        echo $ENV_FILE
        echo $ZENBOT_DB_FILE
        mkdir -p secrets
        cd secrets
        echo $ENV_FILE > .env
        echo $ZENBOT_DB_FILE > zenbot.json
        ls
        cd ..
        ls
    - name: npm install, build, and test
      run: |
        npm install
        npm run unit-test
        # npm run integ-test
