name: Zenbot CI

# PR deploy
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: Shahaed/zenbot@master
    - name: Test
      run: |
        npm i
        npm test
